# -*- coding: utf-8 -*-
"""Copy of Allam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Muz0s1Ns5BEJraOESd0bvnxcjcGm5r94
"""

# Install or upgrade required libraries for QLoRA
!pip install -U bitsandbytes>=0.46.1 accelerate peft trl transformers datasets

# ==========================================
# 1. مكتبات معالجة البيانات والعمليات الأساسية
# ==========================================
import pandas as pd
import numpy as np
import os

# ==========================================
# 2. مكتبات التعلم العميق الأساسية
# ==========================================
import torch

# ==========================================
# 3. مكتبات تجهيز البيانات (Datasets)
# ==========================================
from datasets import Dataset

# ==========================================
# 4. مكتبات النماذج اللغوية (Hugging Face)
# ==========================================
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
    EarlyStoppingCallback
)

# ==========================================
# 5. مكتبات الضبط الدقيق (Fine-tuning & LoRA)
# ==========================================
!pip install trl
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTTrainer

print("✅ تم استدعاء جميع المكتبات بنجاح!")

# ==========================================
# 1. ربط Google Drive ببيئة الكولاب
# ==========================================
from google.colab import drive
drive.mount('/content/drive')

# ==========================================
# 2. تحديد مسار البيانات وقراءتها
# ==========================================
# مسار البيانات الخاص بمشروعك
TRAIN_DATA_PATH = "/content/drive/MyDrive/Project/synthetic_sensitivity_dataset_v3.csv"

print("جاري قراءة ملف البيانات...")
train_data_df = pd.read_csv(TRAIN_DATA_PATH)

# ==========================================
# 3. فحص البيانات (Sanity Check)
# ==========================================
print("\n✅ تم تحميل البيانات بنجاح!")
print(f"عدد الوثائق للتدريب: {len(train_data_df)}")
print("الأعمدة المتوفرة في الملف:", train_data_df.columns.tolist())

# عرض أول 3 صفوف للتأكد من أن البيانات تبدو صحيحة
display(train_data_df.head(3))

# ==========================================
# 1. Imports
# ==========================================
import pandas as pd
import torch
import os
from google.colab import drive
from datasets import Dataset
from huggingface_hub import login
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    EarlyStoppingCallback
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTTrainer, SFTConfig

# ==========================================
# 2. Setup & Authentication
# ==========================================
drive.mount('/content/drive')

# Your Hugging Face Token
HF_TOKEN = "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"
login(token=HF_TOKEN)

# ==========================================
# 3. Data Loading
# ==========================================
TRAIN_DATA_PATH = "/content/drive/MyDrive/Project/synthetic_sensitivity_dataset_v3.csv"
OUTPUT_DIR = "/content/drive/MyDrive/Project/allam_ndmo_lora"

print("Loading dataset...")
train_data_df = pd.read_csv(TRAIN_DATA_PATH)

# ==========================================
# 4. Tokenizer & Formatting
# ==========================================
MODEL_ID = "humain-ai/ALLaM-7B-Instruct-preview"

print("Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

def create_training_prompt(row):
    system_prompt = (
        "أنت خبير في تصنيف الوثائق الإدارية السعودية حسب ضوابط NDMO. "
        "صنف الوثيقة التالية إلى فئة واحدة فقط: (عام، مقيد، سري، سري للغاية). "
        "تذكر: أي بيانات تتعلق بالرعاية الصحية تُصنف دائماً كـ 'مقيد'."
    )
    user_prompt = f"الوثيقة: {row['content']}"
    target_label = row['sensitivity_level']

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
        {"role": "assistant", "content": target_label}
    ]
    formatted_text = tokenizer.apply_chat_template(messages, tokenize=False)
    return {"text": formatted_text}

print("Formatting dataset...")
full_dataset = Dataset.from_pandas(train_data_df)
full_dataset = full_dataset.map(create_training_prompt)

split_dataset = full_dataset.train_test_split(test_size=0.1, seed=42)
train_dataset = split_dataset['train']
eval_dataset = split_dataset['test']

# ==========================================
# 5. QLoRA Model Preparation
# ==========================================
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

print("Loading base model in 4-bit...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto"
)
model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)
model = get_peft_model(model, lora_config)

# ==========================================
# 6. Training Execution (Optimized for L4 GPU)
# ==========================================
training_args = SFTConfig(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=8,      # Increased for L4 power
    gradient_accumulation_steps=4,      # Total batch size = 32
    learning_rate=2e-4,
    num_train_epochs=1,                 # Changed to 1: One epoch is enough for 40k samples
    optim="paged_adamw_8bit",
    bf16=True,                          # L4 supports bf16 natively
    run_name="allam_lora_fast_training",
    eval_strategy="steps",
    eval_steps=200,
    save_strategy="steps",
    save_steps=200,
    logging_steps=20,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="tensorboard",
    dataset_text_field="text",
    max_length=512,
)

trainer = SFTTrainer(
    model=model,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    processing_class=tokenizer,
    args=training_args,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)]
)

# ==========================================
# 7. Start Training & Save
# ==========================================
print("🚀 Starting High-Speed LoRA fine-tuning on L4...")
trainer.train()

# Save final optimized adapter weights
trainer.save_model(OUTPUT_DIR)
print(f"✅ Training complete. Model saved to: {OUTPUT_DIR}")

"""Part 2

"""

# ==========================================
# 5. QLoRA Model Preparation
# ==========================================
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

MODEL_ID = "humain-ai/ALLaM-7B-Instruct-preview"

print("Loading base model in 4-bit...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto"
)

model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)
model = get_peft_model(model, lora_config)
print("✅ Model loaded and LoRA adapters added.")

# ==========================================
import pandas as pd
import torch
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    EarlyStoppingCallback
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTTrainer, SFTConfig

OUTPUT_DIR = "/content/drive/MyDrive/Project/allam_ndmo_lora"
MODEL_ID = "humain-ai/ALLaM-7B-Instruct-preview"

# تحميل التوكنايزر أولاً
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token

def create_training_prompt(row):
    system_prompt = "أنت خبير في تصنيف الوثائق السعودية حسب NDMO. صنف الوثيقة: (عام، مقيد، سري، سري للغاية)."
    user_prompt = f"الوثيقة: {row['content']}"
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
        {"role": "assistant", "content": row['sensitivity_level']}
    ]
    return {"text": tokenizer.apply_chat_template(messages, tokenize=False)}

print("Preparing dataset...")
train_data_df = pd.read_csv("/content/drive/MyDrive/Project/synthetic_sensitivity_dataset_v3.csv")
full_dataset = Dataset.from_pandas(train_data_df)
# تحويل البيانات لتشمل عمود 'text'
full_dataset = full_dataset.map(create_training_prompt)

split_dataset = full_dataset.train_test_split(test_size=0.1, seed=42)
train_dataset = split_dataset['train']
eval_dataset = split_dataset['test']

# ==========================================
# 2. تحميل الموديل
# ==========================================
print("Loading model...")
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto"
)
model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)
model = get_peft_model(model, lora_config)

# ==========================================
# ==========================================
training_args = SFTConfig(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=8,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    num_train_epochs=1,
    optim="paged_adamw_8bit",
    bf16=True,
    run_name="allam_resume",
    eval_strategy="steps",
    eval_steps=200,
    save_strategy="steps",
    save_steps=200,
    logging_steps=20,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    dataset_text_field="text", # الآن العمود موجود ولن يحدث خطأ
    max_length=512,
)

trainer = SFTTrainer(
    model=model,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    processing_class=tokenizer,
    args=training_args,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)]
)

print("🔄 Resuming training...")
trainer.train(resume_from_checkpoint=True)

# الحفظ النهائي
trainer.save_model(OUTPUT_DIR)
print(f"✅ Finished! Model saved to: {OUTPUT_DIR}")

"""FINE TUNING"""

import torch
import pandas as pd
import gc
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# ==========================================
# ==========================================
MODEL_ID = "humain-ai/ALLaM-7B-Instruct-preview"
ADAPTER_PATH = "/content/drive/MyDrive/Project/allam_ndmo_lora"
SAVE_FILE = "/content/drive/MyDrive/Project/allam_final_expert_results.csv"

# ==========================================
=# ==========================================
print("⏳ Loading Base Model & Tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto"
)

print("🚀 Merging your Fine-Tuned Adapters (LoRA)...")
model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)
model.eval()

# ==========================================
#(Inference)
# ==========================================
def classify_expert(text):
    messages = [
        {"role": "system", "content": "أنت خبير في تصنيف الوثائق السعودية حسب NDMO. صنف الوثيقة: (عام، مقيد، سري، سري للغاية)."},
        {"role": "user", "content": f"الوثيقة: {text}"}
    ]

    # تحويل الرسائل إلى IDs واستخراج التنسور مباشرة لتفادي AttributeError
    input_data = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        return_tensors="pt"
    ).to("cuda")

    # التأكد من استخراج التنسور الصحيح (input_ids)
    if hasattr(input_data, 'input_ids'):
        actual_input_ids = input_data.input_ids
    elif isinstance(input_data, dict):
        actual_input_ids = input_data['input_ids']
    else:
        actual_input_ids = input_data

    with torch.no_grad():
        outputs = model.generate(
            input_ids=actual_input_ids,
            max_new_tokens=10,
            do_sample=False, # استخدام Greedy Search لضمان الدقة والثبات
            pad_token_id=tokenizer.pad_token_id
        )


    response = tokenizer.decode(outputs[0][actual_input_ids.shape[1]:], skip_special_tokens=True)
    return response.strip()

#(eval_dataset)
try:
    test_df = eval_dataset.to_pandas()
except NameError:
    print("⚠️ eval_dataset not in memory, loading from Drive...")
    full_df = pd.read_csv("/content/drive/MyDrive/Project/synthetic_sensitivity_dataset_v3.csv")
    test_df = full_df.sample(n=4000, random_state=42) if len(full_df) >= 4000 else full_df

final_predictions = []
actual_labels = test_df['sensitivity_level'].tolist()

print(f"📊 Starting Expert Evaluation on {len(test_df)} documents...")

for i in tqdm(range(len(test_df)), desc="Classifying"):
    try:
        raw_pred = classify_expert(test_df.iloc[i]['content'])

        # تنظيف وضمان مطابقة المخرجات للفئات الأربعة
        if "سري للغاية" in raw_pred: clean_p = "سري للغاية"
        elif "سري" in raw_pred: clean_p = "سري"
        elif "مقيد" in raw_pred: clean_p = "مقيد"
        else: clean_p = "عام"

        final_predictions.append(clean_p)
    except Exception as e:
        final_predictions.append("عام") # قيمة افتراضية في حال الخطأ النادر

    # تنظيف الذاكرة كل 100 وثيقة لضمان عدم حدوث OOM
    if (i + 1) % 100 == 0:
        torch.cuda.empty_cache()
        gc.collect()

# ==========================================

# ==========================================
test_df['predicted_level'] = final_predictions
test_df.to_csv(SAVE_FILE, index=False, encoding='utf-8-sig')

valid_classes = ["عام", "مقيد", "سري", "سري للغاية"]
print("\n" + "="*50)
print("🏆 FINAL EXPERT MODEL REPORT (After Fine-Tuning)")
print("="*50)
print(classification_report(test_df['sensitivity_level'], test_df['predicted_level'], labels=valid_classes))

# رسم مصفوفة الارتباط النهائية
plt.figure(figsize=(10, 8))
cm = confusion_matrix(test_df['sensitivity_level'], test_df['predicted_level'], labels=valid_classes)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=valid_classes, yticklabels=valid_classes)
plt.title('Final Expert Model Confusion Matrix')
plt.show()

!pip install -U bitsandbytes transformers accelerate peft

from google.colab import drive
drive.mount('/content/drive')

import torch
import pandas as pd
import gc
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split # 🟢 إضافة هامة لتقسيم البيانات
import seaborn as sns
import matplotlib.pyplot as plt

# ==========================================
# 1. الإعدادات والمسارات
# ==========================================
MODEL_ID = "humain-ai/ALLaM-7B-Instruct-preview"
ADAPTER_PATH = "/content/drive/MyDrive/Project/allam_ndmo_lora"
SAVE_FILE = "/content/drive/MyDrive/Project/allam_final_expert_results.csv"

# ==========================================
# 2. تحميل الموديل والتوكنايزر ودمج الأوزان
# ==========================================
print("⏳ Loading Base Model & Tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto"
)

print("🚀 Merging your Fine-Tuned Adapters (LoRA)...")
model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)
model.eval()

# ==========================================
# 3. دالة التصنيف الاحترافية (Inference)
# ==========================================
def classify_expert(text):
    messages = [
        {"role": "system", "content": "أنت خبير في تصنيف الوثائق السعودية حسب NDMO. صنف الوثيقة: (عام، مقيد، سري، سري للغاية)."},
        {"role": "user", "content": f"الوثيقة: {text}"}
    ]

    input_data = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        return_tensors="pt"
    ).to("cuda")

    if hasattr(input_data, 'input_ids'):
        actual_input_ids = input_data.input_ids
    elif isinstance(input_data, dict):
        actual_input_ids = input_data['input_ids']
    else:
        actual_input_ids = input_data

    with torch.no_grad():
        outputs = model.generate(
            input_ids=actual_input_ids,
            max_new_tokens=10,
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id
        )

    response = tokenizer.decode(outputs[0][actual_input_ids.shape[1]:], skip_special_tokens=True)
    return response.strip()

# ==========================================
# 4. تقييم الـ 6000 وثيقة (التعديل الجذري هنا 🟢)
# ==========================================
print("⚠️ Loading dataset from Drive and applying strict 70/15/15 split...")
full_df = pd.read_csv("/content/drive/MyDrive/Project/synthetic_sensitivity_dataset_v3.csv")

# تطبيق التقسيم الطبقي المعياري المذكور في المنهجية (استبعاد 85% تدريب+تحقق، والاحتفاظ بـ 15% اختبار)
_, test_df = train_test_split(
    full_df,
    test_size=0.15, # 15% من 40,000 تساوي بالضبط 6,000 وثيقة
    random_state=42, # نفس البذرة العشوائية المذكورة في التقرير لضمان نفس الوثائق
    stratify=full_df['sensitivity_level'] # ضمان توازن الفئات الأربعة
)

final_predictions = []
actual_labels = test_df['sensitivity_level'].tolist()

print(f"📊 Starting Expert Evaluation on {len(test_df)} documents (Should be 6000)...")

for i in tqdm(range(len(test_df)), desc="Classifying"):
    try:
        raw_pred = classify_expert(test_df.iloc[i]['content'])

        if "سري للغاية" in raw_pred: clean_p = "سري للغاية"
        elif "سري" in raw_pred: clean_p = "سري"
        elif "مقيد" in raw_pred: clean_p = "مقيد"
        else: clean_p = "عام"

        final_predictions.append(clean_p)
    except Exception as e:
        final_predictions.append("عام")

    if (i + 1) % 100 == 0:
        torch.cuda.empty_cache()
        gc.collect()

# ==========================================
# 5. حفظ النتائج والتقرير النهائي
# ==========================================
test_df['predicted_level'] = final_predictions
test_df.to_csv(SAVE_FILE, index=False, encoding='utf-8-sig')

valid_classes = ["عام", "مقيد", "سري", "سري للغاية"]
print("\n" + "="*50)
print("🏆 FINAL EXPERT MODEL REPORT (After Fine-Tuning)")
print("="*50)
print(classification_report(test_df['sensitivity_level'], test_df['predicted_level'], labels=valid_classes))

# رسم مصفوفة الارتباط النهائية باللون البرتقالي لتطابق LLaMA
plt.figure(figsize=(8, 6))
cm = confusion_matrix(test_df['sensitivity_level'], test_df['predicted_level'], labels=valid_classes)

# التعديل هنا: تغيير cmap إلى 'Oranges'
sns.heatmap(cm, annot=True, fmt='d', cmap='Oranges', xticklabels=valid_classes, yticklabels=valid_classes)

plt.title('Final Expert Model Confusion Matrix')
plt.show()